import AppNavbar from "../components/AppNavbar";
import AboutHeader from "./AboutHeader";

export default function AboutPage() {
  return (
    <div className="min-vh-100">
      <AppNavbar />
      <main className="container pt-5 mt-4 about-page">
        <div className="row justify-content-center">
          <div className="col-lg-8">
            <AboutHeader />
            <section className="card glass-card about-page-card mb-4 pt-3">
              <div className="card-body about-page-card-body">
              <section className="about-page-section">
              <h2 className="about-page-section-title">What is valuesearch.app?</h2>
                <p className="about-page-lead mb-4">
                  valuesearch.app is an application for exploring potential investment opportunities. 
                  Powered by AI, it allows you to search for stocks by name or ticker symbol to get a 
                  quick assessment of the stock's potential. 
                </p>
                </section>

                <section className="about-page-section">
                  <h2 className="about-page-section-title">How it works</h2>
                  <p>
                    Data from a variety of sources is fed into the{" "}
                    <code className="about-page-code">Qwen3:30B</code> model, which
                    analyses the data and offers its opinion about the investment
                    opportunity.
                  </p>
                  <p>
                    The model uses current quote data (for example, the latest stock
                    price) together with a set of fundamentals data—including metrics
                    such as Price-to-Earnings, Moving Averages, Price-to-Sales,
                    Price-to-Book, and others—to conduct its analysis.
                  </p>
                </section>

                <section className="about-page-section">
                  <h2 className="about-page-section-title">Data refresh schedule</h2>
                  <ul className="about-page-list">
                    <li>
                      Quote data is updated daily at{" "}
                      <strong>5:00 PM US Eastern Time</strong>, Monday through Friday.
                    </li>
                    <li>
                      Fundamentals data is updated once per week at{" "}
                      <strong>5:00 PM US Eastern Time</strong> on Mondays.
                    </li>
                    <li>
                      AI assessments are refreshed over the weekend, beginning at{" "}
                      <strong>12:00 AM US Eastern Time</strong> on Saturdays.
                    </li>
                  </ul>
                </section>

                <section className="about-page-section">
                  <h2 className="about-page-section-title">Accounts and portfolios</h2>
                  <p>
                    Users can create accounts to organise portfolios into{" "}
                    <strong>Avoid</strong>, <strong>Watch</strong>, <strong>Own</strong>,
                    and <strong>Hold</strong> categories while taking notes, setting
                    price targets, and adding labels.
                  </p>
                  <p>
                    Approved accounts also gain access to the raw quote and fundamentals
                    data that the model uses when forming its assessments.
                  </p>
                  <p className="about-page-note mb-0">
                    Account access is subject to approval before full functionality is
                    enabled.
                  </p>
                </section>

                <section className="about-page-section">
                  <h2 className="about-page-section-title">
                    <i className="bi bi-exclamation-triangle-fill about-page-disclaimer-icon" aria-hidden />
                    Important Disclaimer
                  </h2>
                  <p>
                    Nothing on this application should be considered investment advice.
                    This site is for informational and educational purposes only.
                  </p>
                  <p>
                    Artificial intelligence can make mistakes. Ratings, scores, and
                    assessments shown here are generated by AI systems that may be
                    incomplete, outdated, or incorrect. You should not rely on them as
                    the sole basis for any investment decision.
                  </p>
                  <p className="mb-0">
                    The content you see on this page reflects our own opinions and
                    analysis only. It is not a recommendation, solicitation, or advice
                    to buy, sell, or hold any security. Always do your own research and
                    consider consulting a qualified financial advisor before making
                    investment decisions.
                  </p>
                </section>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}

