"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";

const DISCLAIMER_MODAL_ID = "disclaimer-modal";

export default function DisclosureModal() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  const modalEl = (
    <div
      className="modal fade score-breakdown-modal"
      id={DISCLAIMER_MODAL_ID}
      tabIndex={-1}
      aria-labelledby={`${DISCLAIMER_MODAL_ID}-label`}
      aria-hidden="true"
    >
      <div className="modal-dialog modal-dialog-centered">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title" id={`${DISCLAIMER_MODAL_ID}-label`}>
              Important Disclaimer
            </h5>
            <button
              type="button"
              className="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            />
          </div>
          <div className="modal-body">
            <p className="mb-3">
              Nothing on this application should be considered investment advice. This site is for informational and educational purposes only.
            </p>
            <p className="mb-3">
              Artificial intelligence can make mistakes. Ratings, scores, and assessments shown here are generated by AI systems that may be incomplete, outdated, or incorrect. You should not rely on them as the sole basis for any investment decision.
            </p>
            <p className="mb-0">
              The content you see on this page reflects our own opinions and analysis only. It is not a recommendation, solicitation, or advice to buy, sell, or hold any security. Always do your own research and consider consulting a qualified financial advisor before making investment decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <button
        type="button"
        className="btn btn-sm disclaimer-pill-btn"
        data-bs-toggle="modal"
        data-bs-target={`#${DISCLAIMER_MODAL_ID}`}
        aria-label="Read important disclaimer - Must Read"
      >
        ⚠️ Important Disclaimer - Must Read
      </button>
      {mounted && typeof document !== "undefined"
        ? createPortal(modalEl, document.body)
        : null}
    </>
  );
}
